In [1]:
import numpy as np

In [4]:
u = np.array([2,1,3,5])
v = np.array([4,0,1,3])

In [9]:
u.shape, v.shape


((4,), (4,))

In [13]:
def vec_vec_mult(u, v):
    assert u.shape== v.shape

    n = u.shape[0]
    res = 0.0
    for i in range(n):
        res += u[i] * v[i]
    return res  
    

In [17]:
# all are same
vec_vec_mult(u,v) 
np.dot(u, v)
u.dot(v)

np.int64(26)

In [21]:
U = np.array([
    [2,4,1,0],
    [3,1,0,4],
    [1,0,2,5],
    [5,0,1,4]])
U.shape

In [30]:
def mat_vec_mult(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    R = np.zeros(num_rows)
    
    for i in range(num_rows):
        R[i] = vec_vec_mult(U[i], v)
    return R   

In [32]:
mat_vec_mult(U, v)
U.dot(v)

array([ 9, 24, 21, 33])

In [82]:
V = np.array([
    [2,3,1,4],
    [3,0,1,5],
    [3,1,5,2],
    [4,1,0,2]])
V.shape
# V[[0,1,2]]

(4, 4)

In [58]:
def mat_mat_mult(U,V):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]

    R = np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi = V[:,i]
        Uvi = mat_vec_mult(U, vi)
        R[:,i] = Uvi 
            
    return R
    

In [59]:
mat_mat_mult(U,V), U.dot(V)

(array([[19.,  7., 11., 30.],
        [25., 13.,  4., 25.],
        [28., 10., 11., 18.],
        [29., 20., 10., 30.]]),
 array([[19,  7, 11, 30],
        [25, 13,  4, 25],
        [28, 10, 11, 18],
        [29, 20, 10, 30]]))

In [61]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
V_inv = np.linalg.inv(V)
V_inv

array([[-0.11737089, -0.04694836,  0.03286385,  0.31924883],
       [ 0.31924883, -0.27230047, -0.00938967,  0.05164319],
       [-0.02347418, -0.00938967,  0.20657277, -0.13615023],
       [ 0.07511737,  0.23004695, -0.06103286, -0.16431925]])

In [87]:
print(np.round(V_inv.dot(V), decimals=2))

[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0.  0.  0.  1.]]
