In [2]:
import pandas as pd
import numpy as np

In [10]:
# create 2 d array
a= np.array([[1,2,4],[4,7,9],[9,3,8]])
a
a[1,2]

np.int64(9)

In [14]:
a.ndim


2

In [15]:
a.shape

(3, 3)

In [18]:
b = np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [19]:
c = np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [20]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [33]:
np.linspace(0,20,num=9)
np.linspace(0, 20, num=9).reshape(3,3)

array([[ 0. ,  2.5,  5. ],
       [ 7.5, 10. , 12.5],
       [15. , 17.5, 20. ]])

In [51]:
x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([[5, 6, 7],[8,3,9]])
np.concatenate((x, y), axis = 1)
x.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [69]:
x = np.arange(1, 20 , 2)
y = np.arange(30, 11, -2)
x> y

array([False, False, False, False, False, False, False, False,  True,
        True])

In [81]:
x = np.random.randn(4, 4)
y = np.random.randint(low = 20, high= 100, size=(5,5))
y.mean()
y.std()


np.float64(23.04083331826347)